language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t shumyk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shumyk/react-test npm test

after_success:
  - docker build -t shumyk/multi-client ./client
  - docker build -t shumyk/multi-nginx ./nginx
  - docker build -t shumyk/multi-server ./server
  - docker build -t shumyk/multi-worker ./worker

  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub 
  - docker push shumyk/multi-client
  - docker push shumyk/multi-nginx
  - docker push shumyk/multi-server
  - docker push shumyk/multi-worker
