apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: shumyk-rocks-tls
spec:
  secretName: shumyk-rocks-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: shumyk.rocks
  dnsNames:
    - shumyk.rocks
    - www.shumyk.rocks
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - shumyk.rocks
          - www.shumyk.rocks
          